### ISSUE TITLE
Fetching bug

### ISSUE THREAD

**Issue by fadeev** [virgo-project/dither#28]
There is a bug with fetching memos.

To reproduce visit a user profile and open Vue devtools. Notice that there are over 100 memos in Vuex, although the profile may only show 10.

<img width="1465" alt="Screenshot 2020-03-23 at 19 35 08" src="https://user-images.githubusercontent.com/332151/77329653-16701480-6d40-11ea-8c36-dd68ccdaea5f.png">

That's not perfect (a user should not have to download memos that he doesn't see on the page), but it becomes a problem after visiting other pages or even waiting for a short while. Either devtools blow up (this happens so often to me, that it makes it hard to debug the app):

<img width="1465" alt="Screenshot 2020-03-23 at 19 35 48" src="https://user-images.githubusercontent.com/332151/77329796-4f0fee00-6d40-11ea-9fc3-def7b1875133.png">

Or call stack error is raised:

<img width="1193" alt="Screenshot 2020-03-23 at 13 47 58" src="https://user-images.githubusercontent.com/332151/77329849-5fc06400-6d40-11ea-9d4d-fc6da53904eb.png">

**Comment by fadeev** [comment]
I've located the source of the error to the following line in App.vue:

```js
this.following.map(address => this.fetchMemosFromAddress(address));
```

This line makes the user fetch memos uncontrollably. This line also doesn't make sense, because `map` returns an array of `undefined`, which gets discarded. `fetchMemosFromAddress` produces side-effects, and I assume `forEach` was meant to be used to fetch memos for each address. This does not solve the problem above, however.

To fix this I propose we delegate the important task of fetching memos and other page-specific data to pages themselves (and avoid doing that globally in App.vue). For example, a profile page will dispatch events to fetch memos required for this page (and nothing more). So will the home page.

To start doing this, it's important to be able to fetch only the right data, for example, in `AccountsAccount.vue`:

```js
    this.$store.dispatch("memos/fetchAndAdd", {
      limit: 10,
      orderBy: ["timestamp", "desc"],
      where: [
        ["address", "==", this.$route.params.address],
        ["type", "==", "post"]
      ]
    });
```

Fetching posts made from a specific address. I've added `["type", "==", "post"]`, but if fails:

<img width="1480" alt="Screenshot 2020-03-23 at 19 45 47" src="https://user-images.githubusercontent.com/332151/77331514-a9aa4980-6d42-11ea-81c2-9f383d581294.png">

@nylira would like to hear your thoughts on this! If you agree, we should create indexes, so we can query data more precisely (I don't have permissions to do this).

**Comment by nylira** [comment]
Hey Denis, I'm happy to create this index to so that you can resolve this bug. Can you give me the exact Firebase URL from your Chrome console?

**Comment by fadeev** [comment]
https://console.firebase.google.com/v1/r/project/ditherchat/firestore/indexes?create_composite=Ckhwcm9qZWN0cy9kaXRoZXJjaGF0L2RhdGFiYXNlcy8oZGVmYXVsdCkvY29sbGVjdGlvbkdyb3Vwcy9tZW1vcy9pbmRleGVzL18QARoLCgdhZGRyZXNzEAEaCAoEdHlwZRABGg0KCXRpbWVzdGFtcBACGgwKCF9fbmFtZV9fEAI

**Comment by nylira** [comment]
It's ready to go
