### ISSUE TITLE
Proposal - Build a Blockchain-Based Machine Learning Marketplace 

### ISSUE THREAD

**Issue by haymond** [virgo-project/dither#7]
Today there’s a concentration of power with a few data monopolies. 

This has led to the creation of decentralized alternatives. 

1. Twitter -> [Mastodon](https://joinmastodon.org/), [Dither](https://github.com/virgo-project/dither), [Mooncake](https://github.com/desmos-labs/mooncake) 
2. Facebook - > [Voice](https://voice.com/) 
3. Google - > [Cyber](https://cyber.page/) 
4. Amazon -> [OpenBazaar](https://openbazaar.org/) 

In addition, others are working on social media standards. 

1. [ActivityPub](https://www.w3.org/TR/activitypub/) 
2. [BlueSky](https://twitter.com/bluesky?lang=en) 

In my view, building a decentralized solution without [blockchain based machine learning marketplaces](https://medium.com/@FEhrsam/blockchain-based-machine-learning-marketplaces-cb2d4dae2c17) today is equivalent to building Linux in the 90’s without the Web. Linux is a powerful open source alternative to Windows, but without the Internet providing a free distribution channel, it’s impact on Microsoft would have been much smaller. 

The same goes for today’s decentralized solutions. 

## Blockchain-based machine learning marketplaces

[In a post](https://medium.com/@FEhrsam/blockchain-based-machine-learning-marketplaces-cb2d4dae2c17) from Fred Ersham he shares the following: 

> Machine learning models trained on data from blockchain-based marketplaces have the potential to create the world’s most powerful artificial intelligences. They combine two potent primitives: private machine learning, which allows for training to be done on sensitive private data without revealing it, and blockchain-based incentives, which allow these systems to attract the best data and models to make them smarter. The result is open marketplaces where anyone can sell their data and keep their data private, while developers can use incentives to attract the best data for their algorithms to them.
>
> Constructing these systems is challenging and the requisite building blocks are still being created, but simple initial versions look like they are starting to become possible. I believe these marketplaces will transition us out of the current era of Web 2.0 data monopolies into a Web 3.0 era of open competition for data and algorithms, where both are directly monetized.

Continuing...

> First, decentralized machine learning marketplaces can dismantle the data monopolies of the current tech giants. They standardize and commoditize the main source of value creation on the internet for the last 20 years: proprietary data networks and the strong network effects surrounding them. As a result, value creation gets moved up the stack from data to algorithms.
>
> Said another way, they create a direct business model for AI. Both feeding and training it.
>
> Second, they create the most powerful AI systems in the world, attracting the best data and models to them through direct economic incentives. Their strength increases through multi-sided network effects. As the Web 2.0 era data network monopolies become commoditized, they seem like a good candidate for the next re-aggregation point. We are probably a few years out from this, but it seems directionally correct.

Continuing...

> Fourth, they allow us to get the same benefits of the powerful machine-learning based services we are used to from companies like Google and Facebook without giving away our data.
>
> Fifth, machine learning can advance more quickly, as any engineer can access an open marketplace for data, not just a small group of engineers in the large Web 2.0 companies.

Here's one example. 

> **Competition between algorithms** Creates open competition between models/algorithms in places where it previously didn’t exist. Picture a decentralized Facebook with thousands of competing newsfeed algorithms.

## What’s being built today? 

Teams are building data marketplaces where you can buy and sell information in a trustless way. 

1. [ErasureBay](https://medium.com/numerai/introducing-erasurebay-7a5de91b78d2) from [Numerai](https://numer.ai/) 
2. [Commons](https://commons.oceanprotocol.com/) from [Ocean Protocol](https://oceanprotocol.com/) 
3. [Computable](https://computable.io/)

My proposal is to build not just a decentralized social network *but also* a blockchain-based machine learning marketplace. By building both the client & the system, this could change the current technology paradigm. 

We can wait for another team to build such a system, but I think that will be a mistake. How do we know such a system will use Dither as it’s choice? Why not EOS Voice or Mastodon or even Twitter if it becomes decentralized as Jack intends? 

To me, the end goal isn't just a decentralized platform for free speech but much more and despite the challenges of such an endeavor, the bigger risk to me is not building this solution in the first place. That’s why my recommendation is build both systems or partner with another team that plans to. 

If we don't build it, someone else will. 

![img](https://lh4.googleusercontent.com/UVP0nrswM25fGgovdVfH14g2VPkdotmycVZGPfwJMpesbmp-G66lMeFB6C7-quLhBCbuZH1PkO58o0TiMMAkZEa8Dyf_d0nXX3fhUwZgITudmvQpuPSZ-BwKsisbVkI3754oqvFm)From [Placeholder](https://ipfs.io/ipfs/QmZL4eT1gxnE168Pmw3KyejW6fUfMNzMgeKMgcWJUfYGRj/Placeholder%20Thesis%20Summary.pdf)

**Comment by tnachen** [comment]
I'm quite interested in the ML based blockchain marketplace, there is certainly a lot of nuances and choices that has to be made, ultimately has to decide who is the target users and audience this marketplace is built for, given running ML on decentralized data is very limited in functionality today (federated learning, etc). We can approach the same way computable did was to build a decentralized catalog but a centralized data platform to actually run and execute data, etc.

**Comment by nylira** [comment]
I don't think Dither is the right place to build this. A machine-learning marketplace is far too narrow in scope. Dither is a social media project that is meant for everyone.

A more general marketplace though, to sell digital goods and services? That's definitely a good idea.

**Comment by tnachen** [comment]
Ah yes I don't think in the context of Dither it makes sense, in the context of Virgo it could.

**Comment by haymond** [comment]
Right I see this system being useful not only to Dither, which has a newsfeed algorithm, but also to other types of dApps. 

This section may help to clarify this. 

> To illustrate the potential of private machine learning, imagine an app called “The Ultimate Recommender System”. It watches everything you do on your devices: your browsing history, everything you do in your apps, the pictures on your phone, location data, spending history, wearable sensors, text messages, cameras in your home, the camera on your future AR glasses. It then gives you recommendations: the next web site you should visit, article to read, song to listen to, or product to buy.

> This recommender system would be extremely potent. **More than any of the existing data silos of Google, Facebook, or others could ever be because it has a maximally longitudinal view of you and it can learn from data that otherwise would be too private to consider sharing.** Similar to the prior cryptocurrency trading system example, it would work by allowing a marketplace of models focused on different areas (ex: web site recommendations, music) to compete for access to your encrypted data and recommend things to you, and perhaps even pay you for contributing your data or your attention to the recommendations generated.

> Google’s federated learning and Apple’s differential privacy are one step in this private machine learning direction, but still require trust, don’t allow users to directly examine their security, and keep data siloed.

Then he expands on this more here. 

> Third, as the recommender system example shows, search gets inverted. Instead of people searching for products, products search and compete for people (credit to Brad for this framing). Everyone might have personal curation markets, where recommender systems compete to place the most relevant content in their feed, and relevance is defined by the individual

The concepts he's discussing are a bit abstract, because we're still in the early days here, but I think they'll become more clear over time as other teams try to build these systems. Happy to clarify this over a phone call.

**Comment by nylira** [comment]
I'm closing this PR because this feature could not be fit on the current roadmap. https://github.com/virgo-project/dither/blob/develop/docs/roadmap.md
