### ISSUE TITLE
feature: usernames

### ISSUE THREAD

**Issue by nylira** [virgo-project/dither#9]
Here's what's needed for the first implementation for usernames

- [ ] store unique usernames on firestore
- [ ] create a form to allow users to send a Cosmos Hub transaction to reserve one username in return for 1 ATOM
- [ ] form logic should prevent two users from reserving the same username
- [ ] if the user has 1 ATOM and has picked an unreserved username, let the user have it
- [ ] if the user wants to register a different username, they will have to pay 1 ATOM again
- [ ] their previous username is unlocked for someone else to reserve

**Comment by faddat** [comment]
Price seems about right.

Probably wouldn't want to pay much more, though I do wonder about higher pricing for 1,2,3 and 4 letter names.
